/**
 * BIG MOMMA: INVESTORS' WAR - 52 Spaces GDD Data & Animation Registry
 * Authoritative GDD (Game Design Document) dossiers, economic specs, and
 * visual animation profiles for each of the 52 spaces on the circular board.
 */

export type SpaceAnimationType =
  | 'start_vault'
  | 'seed_sprout'
  | 'angel_network'
  | 'seed_accelerator'
  | 'tax_laser'
  | 'metro_transit'
  | 'quantum_qubit'
  | 'strategy_radar_alpha'
  | 'neural_network'
  | 'cloud_datacenter'
  | 'sec_vault'
  | 'biotech_dna'
  | 'cleangrid_wave'
  | 'genomic_scanner'
  | 'immuno_cell'
  | 'intermodal_freight'
  | 'solaris_corona'
  | 'venture_parchment'
  | 'fusion_tokamak'
  | 'apex_pylons'
  | 'liquidity_sanctuary'
  | 'paystream_globe'
  | 'auction_gavel'
  | 'ledgervault_cipher'
  | 'stripeline_rails'
  | 'hyperloop_tube'
  | 'tensor_gpu'
  | 'strategy_chess'
  | 'synthetix_transformer'
  | 'omni_monolith'
  | 'volatility_spikes'
  | 'titan_fortress'
  | 'aerospace_rocket'
  | 'centralbank_shock'
  | 'quantum_reticle'
  | 'orbital_satellite'
  | 'vc_boardroom'
  | 'wallstreet_depth'
  | 'superwealth_scale'
  | 'mayfair_penthouse'
  | 'silicon_garage'
  | 'privateequity_flywheel'
  | 'cybershield_matrix'
  | 'strategy_globe'
  | 'neurolink_interface'
  | 'shipping_armada'
  | 'windfarm_turbines'
  | 'defi_curve'
  | 'auction_dutch'
  | 'sentient_brain'
  | 'megacorp_lattice'
  | 'hedgefund_apex';

export interface SpaceGDDDetail {
  index: number;
  name: string;
  sector: string;
  type: string;
  animationType: SpaceAnimationType;
  accentColor: string;
  secondaryColor: string;
  imageUrl: string;
  tagline: string;
  strategicUtility: string;
  monopolySynergy: string;
  loreDossier: string;
  siblings: number[];
  yieldTierNames: string[];
}

export const SPACE_GDD_REGISTRY: Record<number, SpaceGDDDetail> = {
  0: {
    index: 0,
    name: 'START / GO',
    sector: 'Financial Gateway',
    type: 'start',
    animationType: 'start_vault',
    accentColor: '#10b981',
    secondaryColor: '#34d399',
    imageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'The Central Clearinghouse of the Investors\' War',
    strategicUtility: 'Collect 200 ƁM executive salary upon passing or landing. Restores baseline liquidity for aggressive auction bidding.',
    monopolySynergy: 'Universal transit anchor: Completing a circuit unlocks +50 SP dividend milestones.',
    loreDossier: 'The sovereign threshold where corporate balance sheets are reconciled. Every completed revolution around the financial ring validates your syndicate\'s staying power and unlocks fresh capital disbursements.',
    siblings: [],
    yieldTierNames: ['Transit Dividend: 200 ƁM'],
  },
  1: {
    index: 1,
    name: 'Seed Capital Alpha',
    sector: 'Seed Stage',
    type: 'property',
    animationType: 'seed_sprout',
    accentColor: '#f59e0b',
    secondaryColor: '#fbbf24',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Early-stage disruptive venture pipeline',
    strategicUtility: 'Low capital expenditure entry point. High ROI potential when upgraded with early incubator rounds.',
    monopolySynergy: 'Synergy with #3 and #40: Doubles base rent across Seed Stage and lowers incubator upgrade cost by 15%.',
    loreDossier: 'A scrappy pre-seed laboratory incubating high-beta algorithms. While revenues begin modest at 6 ƁM, full syndicate maturity commands an intimidating 550 ƁM valuation toll.',
    siblings: [1, 3, 40],
    yieldTierNames: ['Base: 6 ƁM', 'Tier 1: 30 ƁM', 'Tier 2: 90 ƁM', 'Tier 3: 270 ƁM', 'Tier 4: 400 ƁM', 'Monopoly Apex: 550 ƁM'],
  },
  2: {
    index: 2,
    name: 'Angel Syndicate',
    sector: 'Venture Capital',
    type: 'market_event',
    animationType: 'angel_network',
    accentColor: '#f59e0b',
    secondaryColor: '#f97316',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80',
    tagline: 'High-Net-Worth Private Syndicate Deck',
    strategicUtility: 'Draw a high-impact dynamic Market Event card with capital infusions, hostile raids, or market swings.',
    monopolySynergy: 'Triggers liquidity events that can swing balance sheet dominance in your favor.',
    loreDossier: 'An exclusive collective of early tech founders and private family offices providing sovereign backing to bold market moves.',
    siblings: [],
    yieldTierNames: ['Market Catalyst Draw'],
  },
  3: {
    index: 3,
    name: 'Seed Capital Beta',
    sector: 'Seed Stage',
    type: 'property',
    animationType: 'seed_accelerator',
    accentColor: '#f59e0b',
    secondaryColor: '#fbbf24',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Series Seed Hardware & Robotics Incubator',
    strategicUtility: 'Key companion to Alpha, locking down the earliest corner of the circular track.',
    monopolySynergy: 'Completes early monopoly with #1 and #40 for relentless early-game bleed against trailing rivals.',
    loreDossier: 'Pioneering specialized micro-robotics and automated logistics prototypes. High traffic frequency ensures steady toll collection from new entrants.',
    siblings: [1, 3, 40],
    yieldTierNames: ['Base: 8 ƁM', 'Tier 1: 40 ƁM', 'Tier 2: 100 ƁM', 'Tier 3: 300 ƁM', 'Tier 4: 450 ƁM', 'Monopoly Apex: 600 ƁM'],
  },
  4: {
    index: 4,
    name: 'Capital Gains Tax',
    sector: 'Regulatory Compliance',
    type: 'penalty',
    animationType: 'tax_laser',
    accentColor: '#f43f5e',
    secondaryColor: '#fb7185',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Sovereign Audit & Tax Enforcement Chamber',
    strategicUtility: 'Enforces mandatory 150 ƁM compliance levy to curtail runaway liquidity.',
    monopolySynergy: 'Can be mitigated or redirected via Strategy Hub tactical abilities.',
    loreDossier: 'Federal tax auditors and anti-trust overseers inspect balance books. Failure to maintain offshore liquidity shields triggers immediate treasury deductions.',
    siblings: [4, 30, 38],
    yieldTierNames: ['Mandatory Penalty: 150 ƁM'],
  },
  5: {
    index: 5,
    name: 'Metro Transit System',
    sector: 'Transport & Logistics',
    type: 'company',
    animationType: 'metro_transit',
    accentColor: '#94a3b8',
    secondaryColor: '#cbd5e1',
    imageUrl: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Subterranean Maglev Transit Arteries',
    strategicUtility: 'First transport utility. Rents scale dynamically based on total transit assets owned (25 ƁM up to 200 ƁM).',
    monopolySynergy: 'Controls the movement corridor alongside #15, #25, #35, and #45.',
    loreDossier: 'High-speed subterranean transit shuttles transporting half a million finance executives across the financial district every hour.',
    siblings: [5, 15, 25, 35, 45],
    yieldTierNames: ['1 System: 25 ƁM', '2 Systems: 50 ƁM', '3 Systems: 100 ƁM', '4+ Systems: 200 ƁM'],
  },
  6: {
    index: 6,
    name: 'Quantum Cyber Lab',
    sector: 'Cyber & Quantum',
    type: 'property',
    animationType: 'quantum_qubit',
    accentColor: '#06b6d4',
    secondaryColor: '#22d3ee',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Cryogenic Qubit Supercomputing Array',
    strategicUtility: 'Foundational quantum computing asset with explosive upper-tier rent milestones.',
    monopolySynergy: 'Pairs with #8, #9, and #42 to control digital defense and decryption monopolies.',
    loreDossier: 'Deep-subzero dilution refrigerators cooling dilution chips to 15 millikelvin, cracking traditional financial cryptography in milliseconds.',
    siblings: [6, 8, 9, 42],
    yieldTierNames: ['Base: 10 ƁM', 'Tier 1: 50 ƁM', 'Tier 2: 150 ƁM', 'Tier 3: 450 ƁM', 'Tier 4: 625 ƁM', 'Monopoly Apex: 750 ƁM'],
  },
  7: {
    index: 7,
    name: 'Strategy Hub Alpha',
    sector: 'Strategy Command',
    type: 'sp_station',
    animationType: 'strategy_radar_alpha',
    accentColor: '#6366f1',
    secondaryColor: '#818cf8',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Tactical War Room & Geopolitical Intelligence',
    strategicUtility: 'Directly credits +25 Strategy Points (SP) to fuel tactical interventions and auction overrides.',
    monopolySynergy: 'Accumulates decisive points for Hostile Takeovers and Shield Activations.',
    loreDossier: 'Military-grade strategy think-tank providing forward predictive models and tactical counter-measures during syndicate disputes.',
    siblings: [7, 27, 36, 43],
    yieldTierNames: ['Resource Gain: +25 SP'],
  },
  8: {
    index: 8,
    name: 'Neural Net Research',
    sector: 'Cyber & Quantum',
    type: 'property',
    animationType: 'neural_network',
    accentColor: '#06b6d4',
    secondaryColor: '#22d3ee',
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Biomimetic Synaptic Computing Institute',
    strategicUtility: 'Affordable cyber sector pillar providing stable cashflow and strategic blockades.',
    monopolySynergy: 'Enhances technological leverage across all Cyber & Quantum holdings.',
    loreDossier: 'Pioneering spiking neuromorphic silicon architectures that process financial market data at the speed of biological reflex arcs.',
    siblings: [6, 8, 9, 42],
    yieldTierNames: ['Base: 10 ƁM', 'Tier 1: 50 ƁM', 'Tier 2: 150 ƁM', 'Tier 3: 450 ƁM', 'Tier 4: 625 ƁM', 'Monopoly Apex: 750 ƁM'],
  },
  9: {
    index: 9,
    name: 'Cloud Fabric Core',
    sector: 'Cyber & Quantum',
    type: 'property',
    animationType: 'cloud_datacenter',
    accentColor: '#06b6d4',
    secondaryColor: '#38bdf8',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Hyperscale Distributed Server Monolith',
    strategicUtility: 'Top-tier cyber asset commanding rents up to 900 ƁM at peak capacity.',
    monopolySynergy: 'Controls the cloud computing backbone required by AI and Fintech sectors.',
    loreDossier: 'Sovereign data centers spanning thousands of server racks, housing redundant fiber transceivers and petabyte cloud caches.',
    siblings: [6, 8, 9, 42],
    yieldTierNames: ['Base: 12 ƁM', 'Tier 1: 60 ƁM', 'Tier 2: 180 ƁM', 'Tier 3: 500 ƁM', 'Tier 4: 700 ƁM', 'Monopoly Apex: 900 ƁM'],
  },
  10: {
    index: 10,
    name: 'SEC Compliance Hold',
    sector: 'Regulatory Sanctuary',
    type: 'rest',
    animationType: 'sec_vault',
    accentColor: '#64748b',
    secondaryColor: '#94a3b8',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Safe Haven Quarantine & Due Diligence Chamber',
    strategicUtility: 'Safe rest space with zero fee exposure. Ideal refuge when opponents hold high-rent sectors.',
    monopolySynergy: 'Allows defensive positioning while competitors exhaust liquidity.',
    loreDossier: 'Neutral regulatory territory where syndicates undergo routine compliance documentation without exposure to aggressive rent tolls.',
    siblings: [10, 20],
    yieldTierNames: ['Status: Neutral Safe Zone'],
  },
  11: {
    index: 11,
    name: 'BioGen Therapeutics',
    sector: 'BioTech',
    type: 'property',
    animationType: 'biotech_dna',
    accentColor: '#10b981',
    secondaryColor: '#34d399',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Precision mRNA & Gene-Editing Foundry',
    strategicUtility: 'Balanced acquisition cost (140 ƁM) with substantial return curve reaching 950 ƁM.',
    monopolySynergy: 'Forms the BioTech trifecta with #13, #14, and #44.',
    loreDossier: 'State-of-the-art biological cleanrooms manufacturing proprietary therapeutic vectors and anti-aging genetic treatments for elite clientele.',
    siblings: [11, 13, 14, 44],
    yieldTierNames: ['Base: 14 ƁM', 'Tier 1: 70 ƁM', 'Tier 2: 200 ƁM', 'Tier 3: 550 ƁM', 'Tier 4: 750 ƁM', 'Monopoly Apex: 950 ƁM'],
  },
  12: {
    index: 12,
    name: 'CleanGrid Utility',
    sector: 'Energy Utility',
    type: 'company',
    animationType: 'cleangrid_wave',
    accentColor: '#eab308',
    secondaryColor: '#facc15',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Municipal Smart Energy Distribution Grid',
    strategicUtility: 'Essential municipal utility. Collects progressive tariffs based on regional energy demand.',
    monopolySynergy: 'Cross-synergy with CleanTech properties (#16, #18, #19).',
    loreDossier: 'Automated substations regulating mega-wattage grid distribution across industrial and residential zones.',
    siblings: [12],
    yieldTierNames: ['Standard Tariff: 20 - 150 ƁM'],
  },
  13: {
    index: 13,
    name: 'GeneTech Diagnostics',
    sector: 'BioTech',
    type: 'property',
    animationType: 'genomic_scanner',
    accentColor: '#10b981',
    secondaryColor: '#34d399',
    imageUrl: 'https://images.unsplash.com/photo-1579165466741-7f35e4755660?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Rapid Genome Sequencing & Biomarker Diagnostics',
    strategicUtility: 'Solid core BioTech asset offering identical high-yield returns as BioGen.',
    monopolySynergy: 'Reinforces the BioTech healthcare monopoly corridor.',
    loreDossier: 'AI-assisted optical sequencers mapping genomic variants in seconds, fueling personalized clinical trials and billion-mark patents.',
    siblings: [11, 13, 14, 44],
    yieldTierNames: ['Base: 14 ƁM', 'Tier 1: 70 ƁM', 'Tier 2: 200 ƁM', 'Tier 3: 550 ƁM', 'Tier 4: 750 ƁM', 'Monopoly Apex: 950 ƁM'],
  },
  14: {
    index: 14,
    name: 'ImmunoHealth Global',
    sector: 'BioTech',
    type: 'property',
    animationType: 'immuno_cell',
    accentColor: '#10b981',
    secondaryColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Sovereign Vaccine & Antibody Bioreactors',
    strategicUtility: 'Apex of the initial BioTech district with 1,000 ƁM maximum toll yield.',
    monopolySynergy: 'Locks down the eastern flank of the circular board.',
    loreDossier: 'Industrial-scale cellular fermentation vats producing monoclonal antibodies and synthetic vaccines for global emergency stockpiles.',
    siblings: [11, 13, 14, 44],
    yieldTierNames: ['Base: 16 ƁM', 'Tier 1: 80 ƁM', 'Tier 2: 220 ƁM', 'Tier 3: 600 ƁM', 'Tier 4: 800 ƁM', 'Monopoly Apex: 1,000 ƁM'],
  },
  15: {
    index: 15,
    name: 'Intermodal Logistics',
    sector: 'Transport & Logistics',
    type: 'company',
    animationType: 'intermodal_freight',
    accentColor: '#94a3b8',
    secondaryColor: '#cbd5e1',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Automated Container Port & Rail Freight Terminal',
    strategicUtility: 'Second transport artery, scaling rent up to 200 ƁM when fleet expands.',
    monopolySynergy: 'Controls global container throughput and supply-chain transit.',
    loreDossier: 'Robotic container cranes and automated rail cars routing forty-foot shipping boxes from deepwater docks to inland distribution hubs.',
    siblings: [5, 15, 25, 35, 45],
    yieldTierNames: ['1 System: 25 ƁM', '2 Systems: 50 ƁM', '3 Systems: 100 ƁM', '4+ Systems: 200 ƁM'],
  },
  16: {
    index: 16,
    name: 'Solaris Renewables',
    sector: 'CleanTech Energy',
    type: 'property',
    animationType: 'solaris_corona',
    accentColor: '#14b8a6',
    secondaryColor: '#2dd4bf',
    imageUrl: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Concentrated Solar Thermal Megafarm',
    strategicUtility: 'Mid-game clean energy powerhouse reaching 1,050 ƁM at apex level.',
    monopolySynergy: 'Combines with #18, #19, and #46 for absolute energy independence.',
    loreDossier: 'Miles of computer-controlled parabolic mirrors concentrating sunlight onto central molten salt towers to produce clean baseload power.',
    siblings: [16, 18, 19, 46],
    yieldTierNames: ['Base: 18 ƁM', 'Tier 1: 90 ƁM', 'Tier 2: 250 ƁM', 'Tier 3: 700 ƁM', 'Tier 4: 875 ƁM', 'Monopoly Apex: 1,050 ƁM'],
  },
  17: {
    index: 17,
    name: 'Venture Syndicate',
    sector: 'Venture Capital',
    type: 'market_event',
    animationType: 'venture_parchment',
    accentColor: '#f59e0b',
    secondaryColor: '#f97316',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Sand Hill Road Term Sheet Syndicate',
    strategicUtility: 'Draw a high-stake Market Event: syndicate recapitalization, regulatory waivers, or liquidity shocks.',
    monopolySynergy: 'Opportunity to alter board dynamics through strategic event cards.',
    loreDossier: 'Private partnership rooms where top-tier venture capitalists draft non-recourse term sheets and negotiate equity carve-outs.',
    siblings: [],
    yieldTierNames: ['Market Catalyst Draw'],
  },
  18: {
    index: 18,
    name: 'Fusion Dynamics',
    sector: 'CleanTech Energy',
    type: 'property',
    animationType: 'fusion_tokamak',
    accentColor: '#14b8a6',
    secondaryColor: '#2dd4bf',
    imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Magnetic Confinement Fusion Reactor',
    strategicUtility: 'High-tech energy cornerstone providing immense late-game rent generation.',
    monopolySynergy: 'Key asset in creating the zero-carbon energy monopoly.',
    loreDossier: 'Superconducting magnetic coils confining deuterium-tritium plasma at 100 million degrees Celsius, realizing limitless commercial fusion.',
    siblings: [16, 18, 19, 46],
    yieldTierNames: ['Base: 18 ƁM', 'Tier 1: 90 ƁM', 'Tier 2: 250 ƁM', 'Tier 3: 700 ƁM', 'Tier 4: 875 ƁM', 'Monopoly Apex: 1,050 ƁM'],
  },
  19: {
    index: 19,
    name: 'Apex Power Grid',
    sector: 'CleanTech Energy',
    type: 'property',
    animationType: 'apex_pylons',
    accentColor: '#14b8a6',
    secondaryColor: '#0d9488',
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Ultra-High-Voltage Continental Transmission Spine',
    strategicUtility: 'The crown of CleanTech Energy with an 1,100 ƁM apex toll.',
    monopolySynergy: 'Locks down the sector before the southern quadrant of the board.',
    loreDossier: 'High-voltage direct current (HVDC) transmission corridors spanning thousands of miles with near-zero line resistance.',
    siblings: [16, 18, 19, 46],
    yieldTierNames: ['Base: 20 ƁM', 'Tier 1: 100 ƁM', 'Tier 2: 300 ƁM', 'Tier 3: 750 ƁM', 'Tier 4: 925 ƁM', 'Monopoly Apex: 1,100 ƁM'],
  },
  20: {
    index: 20,
    name: 'Liquidity Reserve',
    sector: 'Sovereign Treasury',
    type: 'rest',
    animationType: 'liquidity_sanctuary',
    accentColor: '#38bdf8',
    secondaryColor: '#0ea5e9',
    imageUrl: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Subterranean Capital Sanctuary & Bullion Vault',
    strategicUtility: 'Safe harbor capital reserve. Zero fees or tolls incurred while resting here.',
    monopolySynergy: 'Defensive landing spot midway through the 52-space circuit.',
    loreDossier: 'Fortified underground vault rooms storing physical gold bullion and emergency fiat liquidity reserves for member syndicates.',
    siblings: [10, 20],
    yieldTierNames: ['Status: Capital Sanctuary'],
  },
  21: {
    index: 21,
    name: 'PayStream Platform',
    sector: 'Fintech',
    type: 'property',
    animationType: 'paystream_globe',
    accentColor: '#3b82f6',
    secondaryColor: '#60a5fa',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Global Real-Time Micro-Transaction Engine',
    strategicUtility: 'First property of the high-velocity Fintech district (220 ƁM entry, 1,150 ƁM apex).',
    monopolySynergy: 'Synergizes with #23, #24, and #47 to control all electronic retail payment flows.',
    loreDossier: 'Processing over 100,000 transactions per second across 180 currencies with near-zero latency and instant cryptographic settlement.',
    siblings: [21, 23, 24, 47],
    yieldTierNames: ['Base: 22 ƁM', 'Tier 1: 110 ƁM', 'Tier 2: 330 ƁM', 'Tier 3: 800 ƁM', 'Tier 4: 975 ƁM', 'Monopoly Apex: 1,150 ƁM'],
  },
  22: {
    index: 22,
    name: 'High-Frequency Auction',
    sector: 'Trading Floor',
    type: 'auction',
    animationType: 'auction_gavel',
    accentColor: '#06b6d4',
    secondaryColor: '#38bdf8',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Live Floor Asset Auction & Bidding Arena',
    strategicUtility: 'Triggers an immediate live asset auction where players bid ƁM in increments to seize unowned or distressed properties.',
    monopolySynergy: 'Prime opportunity to steal undervalued assets below base cost or drive rivals into bidding wars.',
    loreDossier: 'Fast-paced algorithmic trading pits where syndicates use real-time bids to acquire valuable licenses and corporate stakes.',
    siblings: [22, 48],
    yieldTierNames: ['Interactive Auction Event'],
  },
  23: {
    index: 23,
    name: 'LedgerVault Security',
    sector: 'Fintech',
    type: 'property',
    animationType: 'ledgervault_cipher',
    accentColor: '#3b82f6',
    secondaryColor: '#60a5fa',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Institutional Cold-Storage Cryptographic Vault',
    strategicUtility: 'Fintech stronghold with a steep rent curve topping out at 1,150 ƁM.',
    monopolySynergy: 'Solidifies institutional dominance across the digital asset market.',
    loreDossier: 'Air-gapped hardware security modules housed in nuclear-bunker facilities protecting multi-signature private keys for sovereign funds.',
    siblings: [21, 23, 24, 47],
    yieldTierNames: ['Base: 22 ƁM', 'Tier 1: 110 ƁM', 'Tier 2: 330 ƁM', 'Tier 3: 800 ƁM', 'Tier 4: 975 ƁM', 'Monopoly Apex: 1,150 ƁM'],
  },
  24: {
    index: 24,
    name: 'StripeLine Payments',
    sector: 'Fintech',
    type: 'property',
    animationType: 'stripeline_rails',
    accentColor: '#3b82f6',
    secondaryColor: '#2563eb',
    imageUrl: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Omnichannel Digital Commerce Infrastructure',
    strategicUtility: 'The crown jewel of the southern Fintech district commanding 1,200 ƁM maximum toll.',
    monopolySynergy: 'Completes the southern payment corridor monopoly for massive capital drain.',
    loreDossier: 'Developer-first payment gateway APIs powering e-commerce platforms, recurring subscriptions, and cross-border currency routing.',
    siblings: [21, 23, 24, 47],
    yieldTierNames: ['Base: 24 ƁM', 'Tier 1: 120 ƁM', 'Tier 2: 360 ƁM', 'Tier 3: 850 ƁM', 'Tier 4: 1,025 ƁM', 'Monopoly Apex: 1,200 ƁM'],
  },
  25: {
    index: 25,
    name: 'HyperLoop Express',
    sector: 'Transport & Logistics',
    type: 'company',
    animationType: 'hyperloop_tube',
    accentColor: '#94a3b8',
    secondaryColor: '#cbd5e1',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Supersonic Vacuum Tube Maglev Pod Transit',
    strategicUtility: 'Third transport network asset. Rent scales to 200 ƁM as syndicate controls more transit lines.',
    monopolySynergy: 'Provides seamless intercity passenger and high-priority cargo speed.',
    loreDossier: 'Magnetic levitation capsules traveling through depressurized low-pressure tubes at 700+ mph between financial capitals.',
    siblings: [5, 15, 25, 35, 45],
    yieldTierNames: ['1 System: 25 ƁM', '2 Systems: 50 ƁM', '3 Systems: 100 ƁM', '4+ Systems: 200 ƁM'],
  },
  26: {
    index: 26,
    name: 'Tensor Data Core',
    sector: 'Artificial Intelligence',
    type: 'property',
    animationType: 'tensor_gpu',
    accentColor: '#a855f7',
    secondaryColor: '#c084fc',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    tagline: '100,000 GPU AI Training Supercluster',
    strategicUtility: 'Entry to the elite Artificial Intelligence sector (260 ƁM entry, 1,275 ƁM apex).',
    monopolySynergy: 'Synergizes with #28, #29, and #49 for unmatched tech supremacy.',
    loreDossier: 'Massive liquid-cooled compute facilities dedicated exclusively to pre-training next-generation frontier frontier AI models.',
    siblings: [26, 28, 29, 49],
    yieldTierNames: ['Base: 26 ƁM', 'Tier 1: 130 ƁM', 'Tier 2: 390 ƁM', 'Tier 3: 900 ƁM', 'Tier 4: 1,100 ƁM', 'Monopoly Apex: 1,275 ƁM'],
  },
  27: {
    index: 27,
    name: 'Strategy Hub Beta',
    sector: 'Strategy Command',
    type: 'sp_station',
    animationType: 'strategy_chess',
    accentColor: '#6366f1',
    secondaryColor: '#818cf8',
    imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Strategic Intelligence Headquarters & M&A War Room',
    strategicUtility: 'Awards +30 Strategy Points (SP) to unlock corporate espionage and asset freezing.',
    monopolySynergy: 'Substantially boosts tactical action frequency.',
    loreDossier: 'High-security command center tracking global acquisitions, proxy fights, and competitive intelligence.',
    siblings: [7, 27, 36, 43],
    yieldTierNames: ['Resource Gain: +30 SP'],
  },
  28: {
    index: 28,
    name: 'Synthetix Cognitive',
    sector: 'Artificial Intelligence',
    type: 'property',
    animationType: 'synthetix_transformer',
    accentColor: '#a855f7',
    secondaryColor: '#c084fc',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Autonomous Multimodal Reasoning Models',
    strategicUtility: 'Core AI pillar with punishing rent penalties reaching 1,275 ƁM.',
    monopolySynergy: 'Unlocks deep algorithmic rent extraction across all AI properties.',
    loreDossier: 'Pioneering multimodal transformers capable of automated corporate negotiation, financial modeling, and strategic arbitrage.',
    siblings: [26, 28, 29, 49],
    yieldTierNames: ['Base: 26 ƁM', 'Tier 1: 130 ƁM', 'Tier 2: 390 ƁM', 'Tier 3: 900 ƁM', 'Tier 4: 1,100 ƁM', 'Monopoly Apex: 1,275 ƁM'],
  },
  29: {
    index: 29,
    name: 'Omni Intelligence HQ',
    sector: 'Artificial Intelligence',
    type: 'property',
    animationType: 'omni_monolith',
    accentColor: '#a855f7',
    secondaryColor: '#9333ea',
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Frontier Artificial General Intelligence Campus',
    strategicUtility: 'The undisputed summit of the AI district with a devastating 1,400 ƁM apex toll.',
    monopolySynergy: 'Can bankrupt opponents with a single unfortunate roll.',
    loreDossier: 'The architectural centerpiece of modern silicon intelligence, where self-improving cognitive systems optimize planetary workflows.',
    siblings: [26, 28, 29, 49],
    yieldTierNames: ['Base: 28 ƁM', 'Tier 1: 150 ƁM', 'Tier 2: 450 ƁM', 'Tier 3: 1,000 ƁM', 'Tier 4: 1,200 ƁM', 'Monopoly Apex: 1,400 ƁM'],
  },
  30: {
    index: 30,
    name: 'Market Volatility Fee',
    sector: 'Regulatory Compliance',
    type: 'penalty',
    animationType: 'volatility_spikes',
    accentColor: '#f43f5e',
    secondaryColor: '#fb7185',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Flash Crash Surcharge & Liquidity Buffer',
    strategicUtility: 'Imposes a 100 ƁM market volatility fee on landing syndicates.',
    monopolySynergy: 'Softens opponent capital reserves right before entering the Global Titans district.',
    loreDossier: 'Automatic circuit breaker fee triggered by high-frequency volatility spikes and market imbalances.',
    siblings: [4, 30, 38],
    yieldTierNames: ['Mandatory Penalty: 100 ƁM'],
  },
  31: {
    index: 31,
    name: 'Titan Conglomerate',
    sector: 'Global Titans',
    type: 'property',
    animationType: 'titan_fortress',
    accentColor: '#f43f5e',
    secondaryColor: '#e11d48',
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Multinational Sovereign Enterprise Empire',
    strategicUtility: 'Enters the high-capital Global Titans district (300 ƁM cost, 1,500 ƁM apex toll).',
    monopolySynergy: 'Combines with #32, #34, and #50 for global industrial hegemony.',
    loreDossier: 'A sprawling industrial conglomerate spanning defense manufacturing, consumer electronics, and deep-sea mining concessions.',
    siblings: [31, 32, 34, 50],
    yieldTierNames: ['Base: 30 ƁM', 'Tier 1: 160 ƁM', 'Tier 2: 480 ƁM', 'Tier 3: 1,050 ƁM', 'Tier 4: 1,300 ƁM', 'Monopoly Apex: 1,500 ƁM'],
  },
  32: {
    index: 32,
    name: 'AeroSpace Prime',
    sector: 'Global Titans',
    type: 'property',
    animationType: 'aerospace_rocket',
    accentColor: '#f43f5e',
    secondaryColor: '#e11d48',
    imageUrl: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Orbital Rocket Launch & Satellite Foundry',
    strategicUtility: 'Heavy industrial powerhouse commanding 1,500 ƁM maximum rent.',
    monopolySynergy: 'Dominates the western quadrant with aerospace contracts.',
    loreDossier: 'Reusable orbital rocket launch complexes propelling multi-ton payloads into geosynchronous and deep-space orbits.',
    siblings: [31, 32, 34, 50],
    yieldTierNames: ['Base: 30 ƁM', 'Tier 1: 160 ƁM', 'Tier 2: 480 ƁM', 'Tier 3: 1,050 ƁM', 'Tier 4: 1,300 ƁM', 'Monopoly Apex: 1,500 ƁM'],
  },
  33: {
    index: 33,
    name: 'Central Bank Directive',
    sector: 'Monetary Authority',
    type: 'market_event',
    animationType: 'centralbank_shock',
    accentColor: '#f59e0b',
    secondaryColor: '#d97706',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Federal Reserve Policy & Interest Rate Shock',
    strategicUtility: 'Draws a dynamic central banking directive affecting all active players simultaneously.',
    monopolySynergy: 'Can trigger global yield hikes or asset depreciation waves.',
    loreDossier: 'The high table of central banking governors deciding discount rates, reserve ratios, and quantitative tightening interventions.',
    siblings: [],
    yieldTierNames: ['Macro Policy Event'],
  },
  34: {
    index: 34,
    name: 'Quantum Dynamics Corp',
    sector: 'Global Titans',
    type: 'property',
    animationType: 'quantum_reticle',
    accentColor: '#f43f5e',
    secondaryColor: '#be123c',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Industrial Quantum Defense & Orbital Radar',
    strategicUtility: 'Major titan asset with a crippling 1,600 ƁM apex toll.',
    monopolySynergy: 'Completes titan supremacy across space, defense, and sovereign contracts.',
    loreDossier: 'Pioneering orbital defense grids and quantum-secure satellite telemetry networks for international defense consortiums.',
    siblings: [31, 32, 34, 50],
    yieldTierNames: ['Base: 32 ƁM', 'Tier 1: 175 ƁM', 'Tier 2: 500 ƁM', 'Tier 3: 1,100 ƁM', 'Tier 4: 1,350 ƁM', 'Monopoly Apex: 1,600 ƁM'],
  },
  35: {
    index: 35,
    name: 'Orbital Constellation',
    sector: 'Transport & Logistics',
    type: 'company',
    animationType: 'orbital_satellite',
    accentColor: '#94a3b8',
    secondaryColor: '#cbd5e1',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Low-Earth-Orbit Telecom & Laser Satellite Mesh',
    strategicUtility: 'Fourth transport company. Maximizes transport syndicate toll to 200 ƁM per transit landing.',
    monopolySynergy: 'Completes global coverage from ground, sea, track, and orbit.',
    loreDossier: 'Over 5,000 laser-interlinked microsatellites beaming gigabit internet and high-precision financial trading signals globally.',
    siblings: [5, 15, 25, 35, 45],
    yieldTierNames: ['1 System: 25 ƁM', '2 Systems: 50 ƁM', '3 Systems: 100 ƁM', '4+ Systems: 200 ƁM'],
  },
  36: {
    index: 36,
    name: 'Venture Capital Board',
    sector: 'Strategy Command',
    type: 'sp_station',
    animationType: 'vc_boardroom',
    accentColor: '#6366f1',
    secondaryColor: '#818cf8',
    imageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Elite Investor Assembly & Board Seat Voting Room',
    strategicUtility: 'Awards +35 Strategy Points (SP) to finance major hostile takeovers and portfolio audits.',
    monopolySynergy: 'Enables high-tier SP tactical commands.',
    loreDossier: 'Where sovereign wealth allocators and syndicate managing partners vote on board takeovers and multi-billion-mark capital calls.',
    siblings: [7, 27, 36, 43],
    yieldTierNames: ['Resource Gain: +35 SP'],
  },
  37: {
    index: 37,
    name: 'Wall Street Citadel',
    sector: 'Wall Street Apex',
    type: 'property',
    animationType: 'wallstreet_depth',
    accentColor: '#fbbf24',
    secondaryColor: '#f59e0b',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Ultra-Elite Private Hedge Fund Fortress',
    strategicUtility: 'Pinnacle financial district property (350 ƁM cost, 1,500 ƁM apex toll).',
    monopolySynergy: 'The deadliest district on the board when combined with #39 and #51.',
    loreDossier: 'Legendary quantitative trading tower managing hundreds of billions in algorithmic capital with microsecond co-located exchange feeds.',
    siblings: [37, 39, 51],
    yieldTierNames: ['Base: 35 ƁM', 'Tier 1: 175 ƁM', 'Tier 2: 500 ƁM', 'Tier 3: 1,100 ƁM', 'Tier 4: 1,300 ƁM', 'Monopoly Apex: 1,500 ƁM'],
  },
  38: {
    index: 38,
    name: 'Super-Wealth Assessment',
    sector: 'Regulatory Compliance',
    type: 'penalty',
    animationType: 'superwealth_scale',
    accentColor: '#f43f5e',
    secondaryColor: '#fb7185',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=80',
    tagline: 'High-Net-Worth Sovereign Clawback Chamber',
    strategicUtility: 'Penalizes excess capital with a flat 100 ƁM audit assessment.',
    monopolySynergy: 'Provides a tactical obstacle in the high-stakes northern quadrant.',
    loreDossier: 'Tax magistrates executing statutory clawbacks on excessive corporate liquidity and unrealized balance sheet appreciation.',
    siblings: [4, 30, 38],
    yieldTierNames: ['Mandatory Penalty: 100 ƁM'],
  },
  39: {
    index: 39,
    name: 'Mayfair Financial Tower',
    sector: 'Wall Street Apex',
    type: 'property',
    animationType: 'mayfair_penthouse',
    accentColor: '#fbbf24',
    secondaryColor: '#d97706',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Landmark Skyscraper Penthouse Headquarters',
    strategicUtility: 'One of the most expensive properties in the world (400 ƁM cost, 2,000 ƁM apex toll).',
    monopolySynergy: 'A fully upgraded Mayfair Tower can wipe out entire syndicate reserves in one turn.',
    loreDossier: 'Soaring seventy stories above the city, this glass-and-steel monolith houses private banking suites, sovereign wealth embassies, and gold bullion vaults.',
    siblings: [37, 39, 51],
    yieldTierNames: ['Base: 50 ƁM', 'Tier 1: 200 ƁM', 'Tier 2: 600 ƁM', 'Tier 3: 1,400 ƁM', 'Tier 4: 1,700 ƁM', 'Monopoly Apex: 2,000 ƁM'],
  },
  40: {
    index: 40,
    name: 'Silicon Valley Incubator',
    sector: 'Seed Stage',
    type: 'property',
    animationType: 'silicon_garage',
    accentColor: '#f59e0b',
    secondaryColor: '#fbbf24',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Legendary Startup Garage & Seed Ecosystem',
    strategicUtility: 'Anchor of the Seed Stage district with an 800 ƁM apex toll.',
    monopolySynergy: 'Completes the Seed Stage monopoly alongside #1 and #3.',
    loreDossier: 'Hallowed garage space where epoch-defining tech giants were founded on coffee, whiteboards, and equity promises.',
    siblings: [1, 3, 40],
    yieldTierNames: ['Base: 10 ƁM', 'Tier 1: 50 ƁM', 'Tier 2: 150 ƁM', 'Tier 3: 450 ƁM', 'Tier 4: 600 ƁM', 'Monopoly Apex: 800 ƁM'],
  },
  41: {
    index: 41,
    name: 'Private Equity Fund',
    sector: 'Venture Capital',
    type: 'market_event',
    animationType: 'privateequity_flywheel',
    accentColor: '#f59e0b',
    secondaryColor: '#ea580c',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Leveraged Buyout Consortium & Recapitalization',
    strategicUtility: 'Dynamic Market Event card featuring debt restructuring, hostile board votes, or mega-dividends.',
    monopolySynergy: 'High-stakes catalyst that shifts property titles and player cash reserves.',
    loreDossier: 'Elite private equity partners executing leveraged buyouts to strip inefficiencies and spin off high-value subsidiaries.',
    siblings: [],
    yieldTierNames: ['Market Catalyst Draw'],
  },
  42: {
    index: 42,
    name: 'CyberShield Systems',
    sector: 'Cyber & Quantum',
    type: 'property',
    animationType: 'cybershield_matrix',
    accentColor: '#06b6d4',
    secondaryColor: '#0891b2',
    imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Global Zero-Day Cybersecurity Defense Matrix',
    strategicUtility: 'Reinforces the Cyber sector with steady 900 ƁM maximum toll capacity.',
    monopolySynergy: 'Secures full technological lockdown alongside #6, #8, and #9.',
    loreDossier: 'Automated threat hunting algorithms monitoring dark-web leaks, sovereign ransomware vectors, and infrastructure integrity.',
    siblings: [6, 8, 9, 42],
    yieldTierNames: ['Base: 12 ƁM', 'Tier 1: 60 ƁM', 'Tier 2: 180 ƁM', 'Tier 3: 500 ƁM', 'Tier 4: 700 ƁM', 'Monopoly Apex: 900 ƁM'],
  },
  43: {
    index: 43,
    name: 'Strategy Hub Gamma',
    sector: 'Strategy Command',
    type: 'sp_station',
    animationType: 'strategy_globe',
    accentColor: '#6366f1',
    secondaryColor: '#4f46e5',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Apex Strategic Geopolitical Boardroom',
    strategicUtility: 'The highest-yielding SP station on the board, granting +40 Strategy Points (SP).',
    monopolySynergy: 'Instantly enables decisive game-winning SP ability deployments.',
    loreDossier: 'The grand council room where global monetary treaties are forged and financial war doctrines are signed.',
    siblings: [7, 27, 36, 43],
    yieldTierNames: ['Resource Gain: +40 SP'],
  },
  44: {
    index: 44,
    name: 'NeuroLink Technologies',
    sector: 'BioTech',
    type: 'property',
    animationType: 'neurolink_interface',
    accentColor: '#10b981',
    secondaryColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Direct Neural Interface & Brain-Computer Cybernetics',
    strategicUtility: 'Advanced BioTech holding generating up to 1,000 ƁM at apex capacity.',
    monopolySynergy: 'Crowns the BioTech empire with next-generation human-machine patents.',
    loreDossier: 'Micro-electrode arrays interfacing directly with cortical synapses, allowing instant telemetry between human traders and algorithmic platforms.',
    siblings: [11, 13, 14, 44],
    yieldTierNames: ['Base: 16 ƁM', 'Tier 1: 80 ƁM', 'Tier 2: 220 ƁM', 'Tier 3: 600 ƁM', 'Tier 4: 800 ƁM', 'Monopoly Apex: 1,000 ƁM'],
  },
  45: {
    index: 45,
    name: 'Global Shipping Fleet',
    sector: 'Transport & Logistics',
    type: 'company',
    animationType: 'shipping_armada',
    accentColor: '#94a3b8',
    secondaryColor: '#cbd5e1',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Autonomous Ultra-Large Container Maritime Fleet',
    strategicUtility: 'Fifth and final transport holding, completing the worldwide freight monopoly (up to 200 ƁM rent).',
    monopolySynergy: 'Controls the global sea lanes and raw material supply routes.',
    loreDossier: 'Nuclear-powered, satellite-guided container mega-ships carrying 24,000 TEU across transatlantic and transpacific trade lanes.',
    siblings: [5, 15, 25, 35, 45],
    yieldTierNames: ['1 System: 25 ƁM', '2 Systems: 50 ƁM', '3 Systems: 100 ƁM', '4+ Systems: 200 ƁM'],
  },
  46: {
    index: 46,
    name: 'WindFarm Dynamics',
    sector: 'CleanTech Energy',
    type: 'property',
    animationType: 'windfarm_turbines',
    accentColor: '#14b8a6',
    secondaryColor: '#0f766e',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Deep-Water Offshore Wind Turbine Array',
    strategicUtility: 'Heavy CleanTech asset commanding an 1,100 ƁM apex toll.',
    monopolySynergy: 'Solidifies clean energy dominance alongside #16, #18, and #19.',
    loreDossier: 'Gigantic 15-megawatt wind turbines anchored in deep North Sea waters, harnessing gale-force oceanic currents for clean grid power.',
    siblings: [16, 18, 19, 46],
    yieldTierNames: ['Base: 20 ƁM', 'Tier 1: 100 ƁM', 'Tier 2: 300 ƁM', 'Tier 3: 750 ƁM', 'Tier 4: 925 ƁM', 'Monopoly Apex: 1,100 ƁM'],
  },
  47: {
    index: 47,
    name: 'DeFi Liquidity Pool',
    sector: 'Fintech',
    type: 'property',
    animationType: 'defi_curve',
    accentColor: '#3b82f6',
    secondaryColor: '#1d4ed8',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Algorithmic Automated Market Maker Pool',
    strategicUtility: 'Advanced Fintech asset with an aggressive 1,200 ƁM apex return.',
    monopolySynergy: 'Controls decentralized trading liquidity and automated lending protocols.',
    loreDossier: 'Smart contract liquidity pools locking billions in digital assets, facilitating algorithmic flash loans and arbitrage routing 24/7.',
    siblings: [21, 23, 24, 47],
    yieldTierNames: ['Base: 24 ƁM', 'Tier 1: 120 ƁM', 'Tier 2: 360 ƁM', 'Tier 3: 850 ƁM', 'Tier 4: 1,025 ƁM', 'Monopoly Apex: 1,200 ƁM'],
  },
  48: {
    index: 48,
    name: 'High-Frequency Auction 2',
    sector: 'Trading Floor',
    type: 'auction',
    animationType: 'auction_dutch',
    accentColor: '#06b6d4',
    secondaryColor: '#0284c7',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Flash Pit Asset Auction & Distressed Sale Arena',
    strategicUtility: 'Second interactive live asset auction. Trigger fast bidding rounds to claim prime assets.',
    monopolySynergy: 'Crucial venue for snapping up contested properties before rivals complete sets.',
    loreDossier: 'High-octane financial auction arena where distressed corporate debt and prime real-estate assets change hands in seconds.',
    siblings: [22, 48],
    yieldTierNames: ['Interactive Auction Event'],
  },
  49: {
    index: 49,
    name: 'Sentient AI Labs',
    sector: 'Artificial Intelligence',
    type: 'property',
    animationType: 'sentient_brain',
    accentColor: '#a855f7',
    secondaryColor: '#7e22ce',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Neuromorphic Bio-Digital Intelligence Institute',
    strategicUtility: 'Apex AI property with a punishing 1,400 ƁM maximum toll.',
    monopolySynergy: 'Completes the dominant AI monopoly of the late board.',
    loreDossier: 'Experimental research labs culturing biological neural tissue integrated with silicon substrates to achieve genuine synthetic intuition.',
    siblings: [26, 28, 29, 49],
    yieldTierNames: ['Base: 28 ƁM', 'Tier 1: 150 ƁM', 'Tier 2: 450 ƁM', 'Tier 3: 1,000 ƁM', 'Tier 4: 1,200 ƁM', 'Monopoly Apex: 1,400 ƁM'],
  },
  50: {
    index: 50,
    name: 'MegaCorp Holdings',
    sector: 'Global Titans',
    type: 'property',
    animationType: 'megacorp_lattice',
    accentColor: '#f43f5e',
    secondaryColor: '#9f1239',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    tagline: 'Planetary Sovereign Wealth Holding Entity',
    strategicUtility: 'The peak of the Global Titans sector with a massive 1,600 ƁM apex toll.',
    monopolySynergy: 'Forms the ultimate industrial cartel with #31, #32, and #34.',
    loreDossier: 'A sovereign conglomerate controlling ports, satellite grids, semiconductor foundries, and pharmaceutical giants worldwide.',
    siblings: [31, 32, 34, 50],
    yieldTierNames: ['Base: 32 ƁM', 'Tier 1: 175 ƁM', 'Tier 2: 500 ƁM', 'Tier 3: 1,100 ƁM', 'Tier 4: 1,350 ƁM', 'Monopoly Apex: 1,600 ƁM'],
  },
  51: {
    index: 51,
    name: 'Hedge Fund Citadel',
    sector: 'Wall Street Apex',
    type: 'property',
    animationType: 'hedgefund_apex',
    accentColor: '#fbbf24',
    secondaryColor: '#b45309',
    imageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?auto=format&fit=crop&w=1200&q=80',
    tagline: 'The Pinnacle Fortress of Global High Finance',
    strategicUtility: 'The highest rent on the entire 52-space board: 2,000 ƁM at Apex Headquarters level.',
    monopolySynergy: 'The game-ending anchor of the Wall Street Apex district alongside Mayfair Tower (#39) and Citadel (#37).',
    loreDossier: 'Standing immediately before the Start clearinghouse, this colossal high-frequency algorithmic citadel collects titanic tolls from any rival seeking to complete their circuit.',
    siblings: [37, 39, 51],
    yieldTierNames: ['Base: 50 ƁM', 'Tier 1: 200 ƁM', 'Tier 2: 600 ƁM', 'Tier 3: 1,400 ƁM', 'Tier 4: 1,700 ƁM', 'Monopoly Apex: 2,000 ƁM'],
  },
};
